env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
